<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251117110112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create new table `imports`';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE imports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(9) NOT NULL, last_page INT NOT NULL, last_id INT NOT NULL, imported_count SMALLINT NOT NULL, date DATE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE imports');
    }
}
