<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251116151406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'init schema db with new tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE characters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, gender VARCHAR(7) NOT NULL, status VARCHAR(7) NOT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE episodes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, release_date DATE NOT NULL, season SMALLINT NOT NULL, series SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE episode_character (episode_id INT NOT NULL, character_id INT NOT NULL, PRIMARY KEY (episode_id, character_id))');
        $this->addSql('CREATE INDEX IDX_2DB8260D362B62A0 ON episode_character (episode_id)');
        $this->addSql('CREATE INDEX IDX_2DB8260D1136BE75 ON episode_character (character_id)');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author VARCHAR(150) NOT NULL, text TEXT NOT NULL, publication_date DATE NOT NULL, rating SMALLINT NOT NULL, episode_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0F362B62A0 ON reviews (episode_id)');
        $this->addSql('ALTER TABLE episode_character ADD CONSTRAINT FK_2DB8260D362B62A0 FOREIGN KEY (episode_id) REFERENCES episodes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE episode_character ADD CONSTRAINT FK_2DB8260D1136BE75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F362B62A0 FOREIGN KEY (episode_id) REFERENCES episodes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE episode_character DROP CONSTRAINT FK_2DB8260D362B62A0');
        $this->addSql('ALTER TABLE episode_character DROP CONSTRAINT FK_2DB8260D1136BE75');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F362B62A0');
        $this->addSql('DROP TABLE characters');
        $this->addSql('DROP TABLE episodes');
        $this->addSql('DROP TABLE episode_character');
        $this->addSql('DROP TABLE reviews');
    }
}
